version: '3'

tasks:
  default:
    desc: list tasks
    cmds:
      - task --list-all
  
  cache:
    desc: cache dependencies
    cmds:
      - go fmt ./...
      - go mod tidy

  stop:
    desc: terminate application
    cmds:
      - docker-compose down --volumes

  start:
    desc: run application
    deps:
      - stop
      - cache
    cmds:
      - docker-compose --env-file .env up -d --build --force-recreate

  logs:
    desc: run logs
    cmds:
      - docker-compose logs -f